/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mlrbinder;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.File;
import java.nio.file.Path;

import org.junit.jupiter.api.Test;

class MlrBinderTest {
	@Test
	void pathTest() {
		Path mlrPath = Path.of("mlr");
		MlrBinder mlr = new MlrBinder().path(mlrPath);
		assertEquals(mlrPath, mlr.getPath());
	}
}
