rm help.txt
mlr altkv -h >> help.txt
mlr bar -h >> help.txt
mlr bootstrap -h >> help.txt
mlr cat -h >> help.txt
mlr check -h >> help.txt
mlr clean-whitespace -h >> help.txt
mlr count -h >> help.txt
mlr count-distinct -h >> help.txt
mlr count-similar -h >> help.txt
mlr cut -h >> help.txt
mlr decimate -h >> help.txt
mlr fill-down -h >> help.txt
mlr fill-empty -h >> help.txt
mlr filter -h >> help.txt
mlr flatten -h >> help.txt
mlr format-values -h >> help.txt
mlr fraction -h >> help.txt
mlr gap -h >> help.txt
mlr grep -h >> help.txt
mlr group-by -h >> help.txt
mlr group-like -h >> help.txt
mlr having-fields -h >> help.txt
mlr head -h >> help.txt
mlr histogram -h >> help.txt
mlr join -h >> help.txt
mlr json-parse -h >> help.txt
mlr json-stringify -h >> help.txt
mlr label -h >> help.txt
mlr latin1-to-utf8 -h >> help.txt
mlr utf8-to-latin1 -h >> help.txt
mlr least-frequent -h >> help.txt
mlr merge-fields -h >> help.txt
mlr most-frequent -h >> help.txt
mlr nest -h >> help.txt
mlr nothing -h >> help.txt
mlr put -h >> help.txt
mlr regularize -h >> help.txt
mlr remove-empty-columns -h >> help.txt
mlr rename -h >> help.txt
mlr reorder -h >> help.txt
mlr repeat -h >> help.txt
mlr reshape -h >> help.txt
mlr sample -h >> help.txt
mlr sec2gmt -h >> help.txt
mlr sec2gmtdate -h >> help.txt
mlr seqgen -h >> help.txt
mlr shuffle -h >> help.txt
mlr skip-trivial-records -h >> help.txt
mlr sort -h >> help.txt
mlr sort-within-records -h >> help.txt
mlr split -h >> help.txt
mlr stats1 -h >> help.txt
mlr stats2 -h >> help.txt
mlr step -h >> help.txt
mlr summary -h >> help.txt
mlr tac -h >> help.txt
mlr tail -h >> help.txt
mlr tee -h >> help.txt
mlr template -h >> help.txt
mlr top -h >> help.txt
mlr unflatten -h >> help.txt
mlr uniq -h >> help.txt
mlr unsparsify -h >> help.txt